# Generated by Django 6.0.2 on 2026-08-22 13:31

import django.db.models.deletion
import myapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_payroll_month'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='month',
            field=models.CharField(default=myapp.models._get_current_month, max_length=7),
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('structure', 'month')},
        ),
    ]
